name: tests

on: [push, pull_request]

jobs:
  test:
    needs: format
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
    - name: Install test dependencies
      run: |        
        pip install -r requirements.txt
    - name: pytest
      run: |
         pytest tests dedupe --cov dedupe
    - env:
        COVERALLS_PARALLEL: true
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: job-${{ matrix.os}}-${{ matrix.python-version }}
      name: Submit to coveralls
      run: |
        pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
        coveralls
    - name: black
      run: |
         black . --check
    - name: mypy
      run: |        
        mypy --ignore-missing-imports dedupe
    - name: Integration tests
      # Do everything twice: The first time is training and generates settings,
      # the second time it tests using a static settings file.
      run: |
        python -m pip install -e ./benchmarks
        python benchmarks/benchmarks/canonical.py
        python benchmarks/benchmarks/canonical.py
        python benchmarks/benchmarks/canonical_matching.py
        python benchmarks/benchmarks/canonical_matching.py
        python benchmarks/benchmarks/canonical_gazetteer.py
        python benchmarks/benchmarks/canonical_gazetteer.py
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@57daa114ba54fd8e1c8563e8027325c0bf2f5e80
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
  wheels:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: test
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2    
    - name: Build wheels
      uses: pypa/cibuildwheel@2.6.0
      env:
        CIBW_ARCHS_MACOS: x86_64 arm64 universal2
    - name: Build sdist
      run: |
        pip install build
        python -m build --sdist
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload --skip-existing wheelhouse/*.whl
        twine upload dist/*
      continue-on-error: true
