name: tests

on: [push, pull_request]

jobs:
  format:
    # We want all subsequent steps of CI to refer to the fresh version of code,
    # so run this before anything else.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
      - run: pip install black
      - run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          printenv | grep GITHUB
          git config --global user.name 'fgregg'
          git config --global user.email 'fgregg@users.noreply.github.com'          
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git remote -v
          git branch
          git status
          black .
          git status
          echo ready to commit
          git commit -am "fixup! Format Python code with psf/black pull_request"
          echo ready to push
          git push
  test:
    needs: format
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
        
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
    - name: Install test dependencies
      run: |        
        pip install -r requirements.txt
    - name: pytest
      run: |
         pytest tests dedupe --cov dedupe
    - env:
        COVERALLS_PARALLEL: true
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: job-${{ matrix.os}}-${{ matrix.python-version }}
      name: Submit to coveralls
      run: |
        pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
        coveralls
    - name: flake8
      run: |
         flake8 dedupe tests benchmarks/benchmarks
    - name: mypy
      run: |        
        mypy --ignore-missing-imports dedupe
    - name: Benchmarking & Integration tests
      # From https://github.com/pandas-dev/pandas/blob/60ac973e64ba364b345aea22bf988272536aa42f/.github/workflows/asv-bot.yml
      continue-on-error: true
      run: |
        cd benchmarks
        asv check -E existing
        git remote add upstream https://github.com/dedupeio/dedupe.git
        git fetch upstream
        asv machine --yes
        asv continuous -f 1.1 upstream/main HEAD
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@57daa114ba54fd8e1c8563e8027325c0bf2f5e80
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
  wheels:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: test
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2    
    - name: Build wheels
      uses: pypa/cibuildwheel@2.5.0
      env:
        CIBW_ARCHS_MACOS: x86_64 arm64 universal2
    - name: Build sdist
      run: |
        pip install build
        python -m build --sdist
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload --skip-existing wheelhouse/*.whl
        twine upload dist/*
      continue-on-error: true
